/**
 * End-to-end exercise of the Aux backend, using only the anon key — the same
 * credential the app ships with, so every RLS policy applies exactly as it would
 * to a real user.
 *
 *   node scripts/e2e-backend.mjs
 *
 * Creates two throwaway accounts whose emails deliberately collide on the
 * generated username, because that collision is what broke signup before.
 */

import { readFileSync } from 'node:fs';
import { createClient } from '@supabase/supabase-js';

const env = Object.fromEntries(
  readFileSync(new URL('../.env.local', import.meta.url), 'utf8')
    .split('\n')
    .map((l) => l.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*)$/))
    .filter(Boolean)
    .map((m) => [m[1], m[2].trim()])
);

const URL_ = env.EXPO_PUBLIC_SUPABASE_URL;
const KEY = env.EXPO_PUBLIC_SUPABASE_ANON_KEY;
const fresh = () => createClient(URL_, KEY, { auth: { persistSession: false } });

const steps = [];
const step = async (name, fn) => {
  try {
    steps.push({ name, ok: true, detail: await fn() });
  } catch (e) {
    steps.push({ name, ok: false, detail: e.message });
  }
};
const must = (error, what) => {
  if (error) throw new Error(`${what}: ${error.message}`);
};

// Same 14-char prefix for both, so the second signup MUST take the dedupe path.
const stamp = Date.now().toString(36);
const emailA = `auxtestuserlong+${stamp}a@example.com`;
const emailB = `auxtestuserlong+${stamp}b@example.com`;
const PASS = 'AuxTest2026!pass';

let A, B, loungeId, inviteCode, roomId, trackId;

await step('Sign up user A', async () => {
  A = fresh();
  const { data, error } = await A.auth.signUp({ email: emailA, password: PASS });
  must(error, 'signUp A');
  if (!data.session) throw new Error('no session — "Confirm email" is still ON');
  return `${data.user.id.slice(0, 8)}… signed in immediately`;
});

await step('Sign up user B (forces a username collision)', async () => {
  B = fresh();
  const { data, error } = await B.auth.signUp({ email: emailB, password: PASS });
  must(error, 'signUp B');
  if (!data.session) throw new Error('no session');
  return `${data.user.id.slice(0, 8)}… — the pgcrypto path works`;
});

await step('Profiles auto-created with distinct usernames', async () => {
  const { data: ua } = await A.auth.getUser();
  const { data: ub } = await B.auth.getUser();
  const { data: pa, error: ea } = await A.from('profiles').select('username').eq('id', ua.user.id).single();
  must(ea, 'profile A');
  const { data: pb, error: eb } = await B.from('profiles').select('username').eq('id', ub.user.id).single();
  must(eb, 'profile B');
  if (pa.username === pb.username) throw new Error('usernames collided!');
  return `${pa.username} / ${pb.username}`;
});

await step('A creates a Lounge (owner auto-added by trigger)', async () => {
  const { data: me } = await A.auth.getUser();
  const { data, error } = await A.from('lounges')
    .insert({ name: 'Basement FM', slug: `basement-fm-${stamp}`, owner_id: me.user.id, is_public: false })
    .select()
    .single();
  must(error, 'create lounge');
  loungeId = data.id;
  inviteCode = data.invite_code;
  if (!inviteCode || inviteCode.length !== 8) throw new Error(`bad invite code: ${inviteCode}`);
  return `invite code ${inviteCode} (generated by new_invite_code)`;
});

await step('RLS: B cannot see A private Lounge', async () => {
  const { data, error } = await B.from('lounges').select('id').eq('id', loungeId);
  must(error, 'read lounges as B');
  if (data.length > 0) throw new Error('B could read a private lounge it is not in');
  return 'invisible to a non-member — correct';
});

await step('RLS: B cannot force itself in as owner', async () => {
  const { data: me } = await B.auth.getUser();
  const { error } = await B.from('lounge_members')
    .insert({ lounge_id: loungeId, user_id: me.user.id, role: 'owner' });
  if (!error) throw new Error('THE CRITICAL HOLE IS OPEN — B joined a private lounge as owner');
  return `blocked (${error.code}) — the policy holds`;
});

await step('B joins with the invite code', async () => {
  const { error } = await B.rpc('join_lounge_by_code', { p_code: inviteCode });
  must(error, 'join_lounge_by_code');
  const { data } = await B.from('lounges').select('name').eq('id', loungeId);
  if (data.length !== 1) throw new Error('joined but still cannot see the lounge');
  return 'joined and the lounge is now visible';
});

await step('A starts a Session', async () => {
  const { data: me } = await A.auth.getUser();
  const { data, error } = await A.from('rooms')
    .insert({ lounge_id: loungeId, name: 'Late night', host_id: me.user.id })
    .select()
    .single();
  must(error, 'create room');
  roomId = data.id;
  return `room ${roomId.slice(0, 8)}…`;
});

await step('Catalog is server-owned: a client cannot write tracks', async () => {
  const { error } = await A.from('tracks')
    .insert({ title: 'Midnight City', artist: 'M83', duration_ms: 243000 });
  if (!error) throw new Error('a client wrote to the shared catalog — it is poisonable');
  return `blocked (${error.code}) — only resolve-track may write`;
});

await step('Queue needs a track, which needs the Edge Functions', async () => {
  const { data } = await A.from('tracks').select('id,title').limit(1);
  if (!data || data.length === 0) {
    throw new Error('catalog is empty — deploy search-tracks/resolve-track to populate it');
  }
  trackId = data[0].id;
  return `using "${data[0].title}" from the catalog`;
});

await step('B queues it (anyone in a Session can)', async () => {
  const { error } = await B.rpc('queue_append', { p_room_id: roomId, p_track_id: trackId });
  must(error, 'queue_append');
  const { data } = await B.from('queue_items').select('id').eq('room_id', roomId);
  return `${data.length} item(s) in the queue`;
});

await step('Only the host can drive playback', async () => {
  const { error } = await B.rpc('room_play', { p_room_id: roomId, p_track_id: trackId, p_position_ms: 0 });
  if (!error) throw new Error('a non-host moved playback');
  return `B refused (${error.code}) — correct`;
});

await step('Host plays; the server stamps the timeline', async () => {
  const { data, error } = await A.rpc('room_play', { p_room_id: roomId, p_track_id: trackId, p_position_ms: 0 });
  must(error, 'room_play');
  const row = Array.isArray(data) ? data[0] : data;
  if (!row?.started_at_ms) throw new Error('started_at_ms not set');
  const drift = Math.abs(Number(row.started_at_ms) - Date.now());
  return `started_at_ms set by the DB — ${drift}ms from this machine's clock`;
});

await step('Realtime delivers a playback change', async () => {
  const channel = B.channel(`e2e-room:${roomId}`);
  const got = new Promise((res, rej) => {
    const t = setTimeout(() => rej(new Error('no realtime event within 12s')), 12000);
    channel.on('postgres_changes',
      { event: 'UPDATE', schema: 'public', table: 'rooms', filter: `id=eq.${roomId}` },
      (payload) => { clearTimeout(t); res(payload.new); });
  });
  await new Promise((res, rej) => {
    const t = setTimeout(() => rej(new Error('channel never subscribed')), 12000);
    channel.subscribe((s) => { if (String(s) === 'SUBSCRIBED') { clearTimeout(t); res(); } });
  });
  await new Promise((r) => setTimeout(r, 400));
  await A.rpc('room_pause', { p_room_id: roomId });
  const row = await got;
  await B.removeChannel(channel);
  return `B saw the pause — is_playing=${row.is_playing}`;
});

await step('Chat round-trips', async () => {
  const { data: me } = await B.auth.getUser();
  const { error } = await B.from('messages')
    .insert({ lounge_id: loungeId, room_id: roomId, user_id: me.user.id, body: 'this is the one' });
  must(error, 'send message');
  const { data } = await A.from('messages').select('body').eq('room_id', roomId);
  if (data.length !== 1) throw new Error('A cannot read B message');
  return `A reads B message: "${data[0].body}"`;
});

// ------------------------------------------------------------------ report
console.log('');
for (const s of steps) {
  console.log(`  ${s.ok ? 'PASS' : 'FAIL'}  ${s.name}`);
  console.log(`        ${s.detail}`);
}
const bad = steps.filter((s) => !s.ok).length;
console.log(`\n  ${steps.length - bad}/${steps.length} passed\n`);
process.exit(bad ? 1 : 0);
